name: Deploy

on:
  push:
    branches: [master]
    paths:
      - gateway/**
      - shared/**
      - .github/workflows/deploy.yml
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jkrumm/rollhook-action@v1
        with:
          url: https://rollhook.jkrumm.com
          image_name: image-gen-gateway
          dockerfile: gateway/Dockerfile
          context: .
